"""add_photo_hash

Revision ID: 0a1710f00d0e
Revises: 6f991826ad90
Create Date: 2026-04-04 09:50:21.167646
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision: str = '0a1710f00d0e'
down_revision: Union[str, None] = '6f991826ad90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('photo_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_messages_photo_hash'), 'messages', ['photo_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_photo_hash'), table_name='messages')
    op.drop_column('messages', 'photo_hash')
    # ### end Alembic commands ###
