"""Add IP tracking to User

Revision ID: 6f991826ad90
Revises: a7b4fcd53a85
Create Date: 2026-03-20 11:13:49.277144
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '6f991826ad90'
down_revision: Union[str, None] = 'a7b4fcd53a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'faces', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'])
    op.add_column('users', sa.Column('last_ip', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('allowed_ip', sa.String(length=50), server_default='*', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allowed_ip')
    op.drop_column('users', 'last_ip')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'faces', type_='foreignkey')
    # ### end Alembic commands ###
