"""Add Group is_public

Revision ID: a7b4fcd53a85
Revises: cb41b364090b
Create Date: 2026-03-20 10:31:08.698682
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'a7b4fcd53a85'
down_revision: Union[str, None] = 'cb41b364090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('is_public', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'is_public')
    # ### end Alembic commands ###
