"""Add UniqueConstraint uq_group_telegram_msg

Revision ID: cb41b364090b
Revises: 001_add_indexes
Create Date: 2026-03-19 14:52:15.258260
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers
revision: str = 'cb41b364090b'
down_revision: Union[str, None] = '001_add_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    op.drop_table('identification_queue')
    op.create_foreign_key(None, 'faces', 'messages', ['message_id'], ['id'])
    op.drop_column('faces', 'person_id')
    op.create_foreign_key(None, 'messages', 'groups', ['group_id'], ['id'])
    op.create_unique_constraint('uq_group_telegram_msg', 'messages', ['group_id', 'telegram_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_group_telegram_msg', 'messages', type_='unique')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.add_column('faces', sa.Column('person_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True))
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_table('identification_queue',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('face_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('suggested_person_id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('similarity', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.ENUM('pending', 'confirmed', 'rejected'), nullable=True),
    sa.Column('reviewed_by', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('reviewed_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_table('persons',
    sa.Column('id', mysql.CHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('display_name', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
